### ISSUE TITLE
Update the base os to Rocky Linux 8 & 9

### ISSUE THREAD

**Issue by tuhaihe** [cloudberrydb/bootcamp#35]
I suggest we need to remove the support of CentOS 7.x along with our Cloudberry 1.6.0 release out. And let the BootCamp support Rocky Linux 8 too.

**Comment by tuhaihe** [comment]
@edespino @antoniopetrole how about this idea?

**Comment by antoniopetrole** [comment]
@tuhaihe looks like @edespino took care of this (https://github.com/cloudberrydb/bootcamp/pull/37). I personally don't think it's worth having both Rocky Linux 8 AND Rocky Linux 9 support but I'm open to hearing other peoples thoughts. Reason being is because the differences between the 2 versions aren't super relevant to the objective of this repo which is learning more about Cloudberry and playing around with it. Just my 2 cents

**Comment by tuhaihe** [comment]
Hi @antoniopetrole thanks for your input. Agreed with you.

As Ed is working on this, so close this issue.
